### ISSUE TITLE
Null token returned during sign on

### ISSUE THREAD

**Issue by byroncoughlinSr** [topicquests/qs-demo#51]
When user sign on email and password are sent to retrieve token. If either one are incorrect token can not be created and null response is returned. This does not cause an error and no indication that the sign on was unsuccessful. 
Fix when token is returned as null there should be a notification that there was an issue with sign on

**Comment by maparent** [comment]
Would it help if I threw a 401?

**Comment by maparent** [comment]
I do not think this is done. You already closed this and I reopened. I'll reopen again. Please do not close issues that are not assigned to you.

**Comment by maparent** [comment]
How many times will I have to ask to leave this open?

**Comment by maparent** [comment]
Stop closing this!!!
