### ISSUE TITLE
Return mmowgli-node.vue to dev

### ISSUE THREAD

**Issue by KnowledgeGarden** [topicquests/qs-demo#60]
The latest version of mmowgli-node.vue disappeared and is to now be returned through this issue.

**Comment by KnowledgeGarden** [comment]
Page cleaned up.
Access with http://localhost:8080/node/foo/foo
Known bugs:

- Empty gray boxes at top and bottom left - no clue where they are coming from
- CSS issues with the column headers near the bottom
TO DO:

- After we can make and populate a tree (nodes with child nodes), then make the columns work

**Comment by maparent** [comment]
merged
