### ISSUE TITLE
Conversation node focus in game_play

### ISSUE THREAD

**Issue by byroncoughlinSr** [topicquests/qs-demo#75]
The first node created by quest creator automatically gets assigned as the current node for all guilds registered to that quest. As game continues on the guild leader selects the conversation node that the guild members will be working on. Each member that desires to work on that node would create their own private node. When they are ready to show it to the rest of the guild they change their nodes status to guild draft. The team members will work on those nodes. And when they are ready they will present it to the guild leader. The guild leader will then publish it to the quest.

**Comment by maparent** [comment]
The above is a description of general workflow (may belong in documentation somewhere), but here's what it means for software features:
The game_play should have a pointer to the focus_node, maybe setting it comes with an appropriate permission. This focus_node should be the initial question when it's the only available node. 
Probably a separate change: We should not allow the quest to be past draft stage (and to allow creation of game_play) until the initial question is created.

**Comment by maparent** [comment]
Note that the focus_node field exists; what is needed now is for the front-end to allow to change it by editing game_play. Changing assignment accordingly.
